practica-agenda/agenda/urls.py
from django.urls import path
from . import views
# from agenda.views import inicio


urlpatterns = [
    path("", views.inicio),
    path("", views.inicio, name = 'base'),
    path('createContact/', views.createContact, name = 'createContact'),
    path('editContact/', views.editContact, name = 'editContact'),
    path('editContact/<str:nombre>/', views.editarContacto, name = 'editContact'),
]

# urlpatterns = [
#     path('', inicio, name = 'base.html')
# ]

practica-agenda/practica/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView

from django.conf.urls.static import static
from django.conf import settings

favicon_view = RedirectView.as_view(url='/static/favicon.png', permanent=True)

urlpatterns = [
    re_path(r'^favicon\.ico$', favicon_view),
    path('admin/', admin.site.urls),
    path('', include('agenda.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

practica-agenda/agenda/models.py
from django.db import models
from django.db.models.fields import CharField, IntegerField

ESTADOS = (
    ("AGU", "Aguascalientes"),
    ("BCN", "Baja California"),
    ("BCS", "Baja California Sur"),
    ("CAM", "Campeche"),
    ("CHP", "Chiapas"),
    ("CHH", "Chihuahua"),
    ("CMX", "Ciudad de México"),
    ("COA", "Coahuila"),
    ("COL", "Colima"),
    ("DUR", "Durango"),
    ("GUA", "Guanajuato"),
    ("GRO", "Guerrero"),
    ("HID", "Hidalgo"),
    ("JAL", "Jalisco"),
    ("MEX", "México"),
    ("MIC", "Michoacán"),
    ("MOR", "Morelos"),
    ("NAY", "Nayarit"),
    ("NLE", "Nuevo León"),
    ("OAX", "Oaxaca"),
    ("PUE", "Puebla"),
    ("QUE", "Querétaro"),
    ("ROO", "Quintana Roo"),
    ("SLP", "San Luis Potosí"),
    ("SIN", "Sinaloa"),
    ("SON", "Sonora"),
    ("TAB", "Tabasco"),
    ("TAM", "Tamaulipas"),
    ("TLA", "Tlaxcala"),
    ("VER", "Veracruz"),
    ("YUC", "Yucatán"),
    ("ZAC", "Zacatecas"),
)

TIPOS_TELEFONO = (
    (1, "Casa"),
    (2, "Teléfono móvil"),
)


class Contacto(models.Model):
    nombre = models.CharField(max_length=60)
    apellidos = models.CharField(max_length=120)
    fotografia = models.ImageField(null=True, blank=True)
    fecha_nacio = models.DateField(default=None, null=True, blank=True)

    def __str__(self):
        template = '{0.nombre} {0.apellidos}'
        return template.format(self)

    class Meta:
        verbose_name = "Contacto"
        verbose_name_plural = "Contactos"
    

class Direccion(models.Model):
    contacto = models.ForeignKey("Contacto", on_delete=models.CASCADE)
    calle = models.CharField(max_length=255)
    numero_exterior = models.CharField(max_length=10)
    numero_interior = models.CharField(max_length=10)
    colonia = models.CharField(max_length=255)
    municipio = models.CharField(max_length=255)
    estado = models.CharField(max_length=3, choices=ESTADOS)
    referencias = models.TextField()

    def __str__(self):
        template = '{0.contacto.nombre} {0.calle}'
        return template.format(self)

    class Meta:
        verbose_name = "Dirección"
        verbose_name_plural = "Direcciones"


class Telefono(models.Model):
    contacto = models.ForeignKey("Contacto", on_delete=models.CASCADE)
    tipo = models.IntegerField(choices=TIPOS_TELEFONO)
    alias = models.CharField(max_length=255)
    numero = models.CharField(max_length=50)

    def __str__(self):
        template = '{0.contacto.nombre} {0.numero}'
        return template.format(self)

    class Meta:
        verbose_name = "Teléfono"
        verbose_name_plural = "Teléfonos"

practica-agenda/agenda/forms.py
from django import forms
# from django.forms import ModelForm
from .models import Contacto


# from PIL import Image
# from django.core.files.uploadedfile import SimpleUploadedFile

from django.core.files.uploadedfile import SimpleUploadedFile

class ContactoForm(forms.ModelForm):
  class Meta:
    model = Contacto
    fields = '__all__'





# class ContactoForm(ModelForm):
#   class Meta:
#     model = Contacto
#     fields = '__all__'

practica-agenda/agenda/views.py
from django.shortcuts import render, redirect
from django.template.loader import get_template
from django.http import HttpResponse
from .models import Contacto

from .forms import ContactoForm
# from .forms import ContactoForm


def inicio(request):
    template = get_template("base.html")
    contactos = Contacto.objects.all()

    print(contactos)

    context = {
        "contactos": contactos,
        "titulo": "Inicio"
    }

    return HttpResponse(template.render(context), request)





def createContact(request):
    # template = get_template("createContact.html")
    # context = {
    #     "titulo": "Crear Contacto"
    # }

    if request.method == 'GET':
        form = ContactoForm()
        context = {
            'form': form
        }
    else:
        form = ContactoForm(request.POST)
        context = {
            'form': form
        }
        if form.is_valid():
            form.save()
            return redirect('editContact')

    # return HttpResponse(template.render(context), request)
    return render(request, 'createContact.html', context)





def editContact(request):
    template = get_template("editContact.html")

    context = {
        "titulo": "Editar Contacto"
    }

    return HttpResponse(template.render(context), request)





def editarContacto(request, nombre):
    contacto = Contacto.objects.get(nombre = nombre)
    if request.method == 'GET':
        form = ContactoForm(instance = contacto)
        context = {
            'form': form
        }
    return render(request, 'editContact.html', context)

practica-agenda/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es-mx">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} Inicio {% endblock title %}</title>

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>

  <body>
    <div class="main">
      <nav class="navbar bg-dark text-white">

        {% block title_agenda %}
          <span class="navbar-brand mb-0 h1">Agenda - Contactos</span>
        {% endblock title_agenda %}

      </nav>



      {% block btn_agregar_contacto %}
      <div class="row p-0 m-0">
        <div class="block-addItem col-12 pt-4">
          <div class="row align-items-center justify-content-center">
            <div class="col-md-12 col-12 col-lg-6 m-0 d-flex justify-content-end pr-3 pr-sm-4 pr-lg-0">
              <a class="btn btn-primary mr-md-2 mr-lg-0" href="{% url 'createContact' %}" role="button">Agregar contacto</a>
            </div>
          </div>
        </div>
      </div>
      {% endblock btn_agregar_contacto %}



      {% block cuerpo_acciones %}

      {% endblock cuerpo_acciones %}


      {% block list_contactos_agregados %}




      
      <div class="row p-0 m-0">
        <div class="col-12 row p-0 pt-4 m-0 justify-content-center">
          <form class="form-container border rounded col-11 col-lg-6 p-0">
            <div class="form__body py-3 px-4 block-overflow block-overflow--list">
              <div>
                <div class="row p-0 m-0">
                  <div class="col-12 p-0 m-0">
                    <div class="row p-0 m-0">

                      {% for contacto in contactos %}
                      <div class="block-contact form-group col-12 p-0 py-3 m-0 border-bottom d-flex align-items-center justify-content-between">
                        <div>
                          <div class="d-flex align-items-center">
                            <span class="font-weight-bold">{{ contacto.nombre }} {{ contacto.apellidos }}</span>
                          </div>
      
                          <div>
                            <a class="badge badge-secondary" href="{% url 'editContact' contacto.nombre %}" role="button">Editar</a>
                            <a class="badge badge-danger" href="#" role="button">Eliminar</a>
                          </div>
                        </div>
      
                        <div class="text-dark">
                          <span>{{ contacto.fecha_nacio }}</span>
                        </div>
                      </div>
                      {% endfor %}

                    </div>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
      {% endblock list_contactos_agregados %}



      <div class="py-3 bar bar--footer position-fixed bg-light"></div>
    </div>

    <script src="{% static 'jquery/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'prueba/gijgo.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
  </body>
</html>

practica-agenda/templates/base1.html
  <body>
    <div class="main">
      <nav class="navbar bg-dark text-white">
        <span class="navbar-brand mb-0 h1">Agenda - Contactos</span>
        <span class="navbar-brand mb-0 h1">Agenda - Nuevo</span>
        <span class="navbar-brand mb-0 h1">Agenda - Editar</span>
      </nav>

      <div class="row p-0 m-0">
        <div class="block-addItem col-12 pt-4">
          <div class="row align-items-center justify-content-center">
            <div class="col-md-12 col-12 col-lg-6 m-0 d-flex justify-content-end pr-3 pr-sm-4 pr-lg-0">
              <a class="btn btn-primary mr-md-2 mr-lg-0" href="#" role="button">Agregar contacto</a>
            </div>
          </div>
        </div>

        <div class="col-12 row p-0 pt-4 m-0 justify-content-center">
          <form class="form-container border rounded col-11 col-lg-6 p-0">
            <div class="form__body py-3 px-4">

              <div class="">
                <div class="row p-0 m-0">
                  <div class="col-12 p-0 m-0">
                    <div class="row p-0 m-0">
                      <div class="form-group col-12 p-0">
                        <label for="InputNombres">Nombres*</label>
                        <input type="text" class="form-control" id="InputNombres">
                      </div>
                
                      <div class="form-group col-12 p-0">
                        <label for="InputApellidos">Apellidos*</label>
                        <input type="text" class="form-control" id="InputApellidos">
                      </div>
                
                      <div class="form-group col-12 p-0">
                        <label for="InputNombres">Fotografia*</label>
                
                        <div class="custom-file">
                          <input type="file" class="custom-file-input" id="customFile">
                          <label class="custom-file-label" for="customFile">---</label>
                        </div>
                      </div>
                
                      <div class="form-group col-12 p-0">
                        <label for="InputApellidos">Fecha de nacimiento</label>
                        <input id="datepicker" />
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div>
                <div class="row p-0 m-0">
                  <div class="col-12 p-0 m-0">
                    <div class="row p-0 m-0">
                      <div class="block-contact form-group col-12 p-0 pb-3 m-0 border-bottom d-flex align-items-center justify-content-between">
                        <div>
                          <div class="d-flex align-items-center">
                            <span class="font-weight-bold">Felipe Diaz</span>
                          </div>

                          <div>
                            <a class="badge badge-secondary" href="#" role="button">Editar</a>
                            <a class="badge badge-danger" href="#" role="button">Eliminar</a>
                          </div>
                        </div>

                        <div class="text-dark">
                          <span>12 de mayo</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="">
                <nav>
                  <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <a class="nav-link active" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="true">Contacto</a>
                    <a class="nav-link" id="nav-address-tab" data-toggle="tab" href="#nav-address" role="tab" aria-controls="nav-address" aria-selected="false">Direccion</a>
                    <a class="nav-link" id="nav-phone-tab" data-toggle="tab" href="#nav-phone" role="tab" aria-controls="nav-phone" aria-selected="false">Telefonos</a>
                  </div>
                </nav>

                <div class="tab-content" id="nav-tabContent">
                  <div class="tab-pane fade show active" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
                    <div class="row p-0 m-0 block-overflow block-overflow--contact">
                      <div class="form-row col-12 px-0 py-0 pt-3 m-0">
                        <div class="form-group col-12 col-md-6">
                          <label for="inputStreet">Nombres*</label>
                          <input type="text" class="form-control" id="inputStreet">
                        </div>

                        <div class="form-group col-12 col-md-6">
                          <label for="inputNumExt">Apellidos*</label>
                          <input type="text" class="form-control" id="inputNumExt">
                        </div>

                        <div class="form-group col-12">
                          <label for="InputNombres">Fotografia*</label>

                          <fieldset class="block-disabled row col-12 m-0 mb-1 p-0 flex-row-reverse" disabled>
                            <label for="disabledTextInput" class="col-3 d-flex align-items-center justify-content-center p-0 m-0">Actualmente</label>
                            <input type="text" id="disabledTextInput" class="form-control col-9 disabledTextInput border-0" placeholder="Disabled input">
                          </fieldset>

                          <div class="custom-file">
                            <input type="file" class="custom-file-input" id="customFile">
                            <label class="custom-file-label" for="customFile">---</label>
                          </div>
                        </div>

                        <div class="form-group col-12">
                          <label for="InputApellidos">Fecha de nacimiento</label>
                          <input id="datepicker" />
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="tab-pane fade" id="nav-address" role="tabpanel" aria-labelledby="nav-address-tab">
                    <div class="row p-0 m-0 block-overflow block-overflow--address">
                        <div class="form-row col-12 px-0 py-0 pt-3 m-0">
                          <div class="form-group col-12 col-md-4">
                            <label for="inputStreet">Calle*</label>
                            <input type="text" class="form-control" id="inputStreet">
                          </div>

                          <div class="form-group col-6 col-md-4">
                            <label for="inputNumExt">Numero exterior*</label>
                            <input type="text" class="form-control" id="inputNumExt">
                          </div>

                        <div class="form-group col-6 col-md-4">
                          <label for="inputNumInt">Numero interior*</label>
                          <input type="text" class="form-control" id="inputNumInt">
                        </div>

                        <div class="form-group col-12 col-sm-4">
                          <label for="inputCol">Colonia*</label>
                          <input type="text" class="form-control" id="inputCol">
                        </div>

                          <div class="form-group col-12 col-sm-4">
                            <label for="inputMuni">Municipio*</label>
                            <input type="text" class="form-control" id="inputMuni">
                          </div>

                          <div class="form-group col-12 col-sm-4">
                            <label for="inputState">Estado*</label>
                            <select id="inputState" class="form-control">
                              <option selected>Choose...</option>
                              <option>...</option>
                            </select>
                          </div>

                          <div class="form-group col-12">
                            <label for="FormControlRef">Referencias*</label>
                            <textarea class="form-control" id="FormControlRef" rows="3"></textarea>
                          </div>
                        </div>
                    </div>
                  </div>

                  <div class="tab-pane fade" id="nav-phone" role="tphone" aria-labelledby="nav-phone-tab">
                    <div class="row p-0 m-0">
                      <div class="col-12 px-0 py-0 pt-3 m-0 d-flex justify-content-end">
                        <a class="btn btn-primary" href="#" role="button">Agregar telefono</a>
                      </div>
                    </div>

                    <div class="row p-0 m-0 mt-2 block-overflow block-overflow--phone">
                      <div class="form-row col-12 px-0 py-0 pt-3 m-0">
                        <div class="form-group col-12 col-md-3">
                          <label for="inlineFormCustomSelect">Tipo*</label>
                          <select class="custom-select mr-5" id="inlineFormCustomSelect">
                            <option selected>Choose...</option>
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                          </select>
                        </div>

                        <div class="form-group col-12 col-md-3">
                          <label for="inputAlias">Alias*</label>
                          <input type="text" class="form-control" id="inputAlias">
                        </div>

                        <div class="form-group col-12 col-md-3">
                          <label for="inputPhone">Numero*</label>
                          <input type="text" class="form-control" id="inputPhone">
                        </div>

                        <div class="form-group col-12 col-md-3 d-flex align-items-end justify-content-center">
                          <a class="btn btn-outline-danger cancelPhone" href="#" role="button">Cancelar</a>
                          <a class="btn btn-outline-danger deletePhone" href="#" role="button">Eliminar</a>
                        </div>
                      </div>

                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="form__footer py-3 px-4 bg-light">
              <div class="form__footer__block1 d-flex justify-content-end align-items-center">
                <button type="submit" class="btn btn-outline-danger mr-1">Cancelar</button>
                <button type="submit" class="btn btn-primary ml-1">Crear Contacto</button>
              </div>

              <div class="form__footer__block2 d-flex justify-content-end align-items-center">
                <button type="submit" class="btn btn-outline-secondary mr-1">Regresar</button>
                <button type="submit" class="btn btn-success ml-1">Actualizar Contacto</button>
              </div>
            </div>
          </form>
        </div>
      </div>

      <div class="py-3 bar bar--footer position-fixed bg-light"></div>
    </div>

    <script src="{% static 'jquery/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'prueba/gijgo.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
  </body>

practica-agenda/templates/createContact.html
{% extends 'base.html' %}

{% block title %}
  Crear Contacto
{% endblock title %}

{% block title_agenda %}
  <span class="navbar-brand mb-0 h1">Agenda - Nuevo</span>
{% endblock title_agenda %}

{% block btn_agregar_contacto %} {% endblock btn_agregar_contacto %}

{% block cuerpo_acciones %}

  <div class="row p-0 m-0">
    <div class="col-12 row p-0 pt-4 m-0 justify-content-center">
      <form class="form-container border rounded col-11 col-lg-6 p-0" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <!-- {{ form }} -->
        <div class="form__body py-3 px-4">
          <div class="">
            <div class="row p-0 m-0">
              <div class="col-12 p-0 m-0">
                <div class="row p-0 m-0">

                  <div class="form-group col-12 p-0">
                    <label for="id_nombre">Nombre*</label>
                    <input type="text" name="nombre" maxlength="60" required class="form-control" id="id_nombre">
                  </div>
            
                  <div class="form-group col-12 p-0">
                    <label for="id_apellidos">Apellidos*</label>
                    <input type="text" name="apellidos" maxlength="120" required class="form-control" id="id_apellidos">
                  </div>

                  <div class="form-group col-12 p-0">
                    <label for="id_fotografia">Fotografia*</label>
            
                    <div class="custom-file">
                      <input type="file" class="custom-file-input" name="fotografia" accept="image/*" id="id_fotografia">
                      <label class="custom-file-label" for="id_fotografia">Choose file</label>
                    </div>
                  </div>

                  <div class="form-group col-12 p-0">
                    <label for="id_fecha_nacio">Fecha nacimiento:</label>
                    <input type="text" name="fecha_nacio" id="id_fecha_nacio" class="datepickerNew">
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="form__footer py-3 px-4 bg-light">
          <div class="form__footer__block1 d-flex justify-content-end align-items-center">
            <a class="btn btn-outline-danger mr-1" href="{% url 'base' %}" role="button">Cancelar</a>
            <button type="submit" class="btn btn-primary ml-1">Crear Contacto</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock cuerpo_acciones %}

{% block list_contactos_agregados %}{% endblock list_contactos_agregados %}

practica-agenda/templates/editContact.html
{% extends 'base.html' %}

{% block title %}
  Editar Contacto
{% endblock title %}

{% block title_agenda %}
  <span class="navbar-brand mb-0 h1">Agenda - Editar</span>
{% endblock title_agenda %}

{% block btn_agregar_contacto %} {% endblock btn_agregar_contacto %}

{% block cuerpo_acciones %}
  <div class="row p-0 m-0">
    <div class="col-12 row p-0 pt-4 m-0 justify-content-center">
      <form class="form-container border rounded col-11 col-lg-6 p-0">
        {% csrf_token %} 
        <div class="form__body py-3 px-4">
          <div class="">
            <nav>
              <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <a class="nav-link active" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="true">Contacto</a>
                <a class="nav-link" id="nav-address-tab" data-toggle="tab" href="#nav-address" role="tab" aria-controls="nav-address" aria-selected="false">Direccion</a>
                <a class="nav-link" id="nav-phone-tab" data-toggle="tab" href="#nav-phone" role="tab" aria-controls="nav-phone" aria-selected="false">Telefonos</a>
              </div>
            </nav>

            <div class="tab-content" id="nav-tabContent">
              <div class="tab-pane fade show active" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
                <div class="row p-0 m-0 block-overflow block-overflow--contact">
                  <div class="form-row col-12 px-0 py-0 pt-3 m-0">
                    <div class="form-group col-12 col-md-6">
                      <label for="inputStreet">Nombres*</label>
                      <input type="text" class="form-control" id="inputStreet">
                    </div>

                    <div class="form-group col-12 col-md-6">
                      <label for="inputNumExt">Apellidos*</label>
                      <input type="text" class="form-control" id="inputNumExt">
                    </div>

                    <div class="form-group col-12">
                      <label for="InputNombres">Fotografia*</label>

                      <fieldset class="block-disabled row col-12 m-0 mb-1 p-0 flex-row-reverse" disabled>
                        <label for="disabledTextInput" class="col-3 d-flex align-items-center justify-content-center p-0 m-0">Actualmente</label>
                        <input type="text" id="disabledTextInput" class="form-control col-9 disabledTextInput border-0" placeholder="Disabled input">
                      </fieldset>

                      <div class="custom-file">
                        <input type="file" class="custom-file-input" id="customFile">
                        <label class="custom-file-label" for="customFile">---</label>
                      </div>
                    </div>

                    <div class="form-group col-12">
                      <label for="InputApellidos">Fecha de nacimiento</label>
                      <input id="datepicker" class="datepickerEdit" />
                    </div>
                  </div>
                </div>
              </div>

              <div class="tab-pane fade" id="nav-address" role="tabpanel" aria-labelledby="nav-address-tab">
                <div class="row p-0 m-0 block-overflow block-overflow--address">
                    <div class="form-row col-12 px-0 py-0 pt-3 m-0">
                      <div class="form-group col-12 col-md-4">
                        <label for="inputStreet">Calle*</label>
                        <input type="text" class="form-control" id="inputStreet">
                      </div>

                      <div class="form-group col-6 col-md-4">
                        <label for="inputNumExt">Numero exterior*</label>
                        <input type="text" class="form-control" id="inputNumExt">
                      </div>

                    <div class="form-group col-6 col-md-4">
                      <label for="inputNumInt">Numero interior*</label>
                      <input type="text" class="form-control" id="inputNumInt">
                    </div>

                    <div class="form-group col-12 col-sm-4">
                      <label for="inputCol">Colonia*</label>
                      <input type="text" class="form-control" id="inputCol">
                    </div>

                      <div class="form-group col-12 col-sm-4">
                        <label for="inputMuni">Municipio*</label>
                        <input type="text" class="form-control" id="inputMuni">
                      </div>

                      <div class="form-group col-12 col-sm-4">
                        <label for="inputState">Estado*</label>
                        <select id="inputState" class="form-control">
                          <option selected>Choose...</option>
                          <option>...</option>
                        </select>
                      </div>

                      <div class="form-group col-12">
                        <label for="FormControlRef">Referencias*</label>
                        <textarea class="form-control" id="FormControlRef" rows="3"></textarea>
                      </div>
                    </div>
                </div>
              </div>

              <div class="tab-pane fade" id="nav-phone" role="tphone" aria-labelledby="nav-phone-tab">
                <div class="row p-0 m-0">
                  <div class="col-12 px-0 py-0 pt-3 m-0 d-flex justify-content-end">
                    <a class="btn btn-primary" href="#" role="button">Agregar telefono</a>
                  </div>
                </div>

                <div class="row p-0 m-0 mt-2 block-overflow block-overflow--phone">
                  <div class="form-row col-12 px-0 py-0 pt-3 m-0">
                    <div class="form-group col-12 col-md-3">
                      <label for="inlineFormCustomSelect">Tipo*</label>
                      <select class="custom-select mr-5" id="inlineFormCustomSelect">
                        <option selected>Choose...</option>
                        <option value="1">One</option>
                        <option value="2">Two</option>
                        <option value="3">Three</option>
                      </select>
                    </div>

                    <div class="form-group col-12 col-md-3">
                      <label for="inputAlias">Alias*</label>
                      <input type="text" class="form-control" id="inputAlias">
                    </div>

                    <div class="form-group col-12 col-md-3">
                      <label for="inputPhone">Numero*</label>
                      <input type="text" class="form-control" id="inputPhone">
                    </div>

                    <div class="form-group col-12 col-md-3 d-flex align-items-end justify-content-center">
                      <a class="btn btn-outline-danger cancelPhone" href="#" role="button">Cancelar</a>
                      <a class="btn btn-outline-danger deletePhone" href="#" role="button">Eliminar</a>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="form__footer py-3 px-4 bg-light">
          <div class="form__footer__block2 d-flex justify-content-end align-items-center">
            <button type="submit" class="btn btn-outline-secondary mr-1">Regresar</button>
            <button type="submit" class="btn btn-success ml-1">Actualizar Contacto</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock cuerpo_acciones %}

{% block list_contactos_agregados %}{% endblock list_contactos_agregados %}